Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 3600
  config.winrm.retry_limit = 600
  config.winrm.retry_delay = 15
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.hostname = "eplan-base"

  # RDP port forward (host → guest)
  config.vm.network "forwarded_port",
    guest: 3389, host: 13389, host_ip: "127.0.0.1", auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "eplan-base"
    vb.memory = 16384          # 16 GB
    vb.cpus   = 8
    vb.gui    = false           # <-- see the desktop while installing
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  # Enable RDP (runs once, very fast)
  config.vm.provision "shell", inline: <<-POWERSHELL
    Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server' `
                     -Name "fDenyTSConnections" -Value 0
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
  POWERSHELL
end
