// src/utils/mechanical/ek36.ts
//
// The EK36 estimate sheet: which baskets a cell picks up, and what
// each basket consists of. Generated from the Eplanix MVC app's own
// catalogue — see parts.ts for where the parts themselves are described.

import { MechanicalCatalog, When } from './catalog';

export const EK36_CATALOG: MechanicalCatalog = {
  panelType: 'EK36',
  baskets: [
  { group: 'FeederTruck', sizes: ['Feeder Truck'] },
  { group: 'VcbTruck', sizes: ['Feeder Truck'], when: When.vcb },
  { group: 'RearVtTruck', sizes: ['Feeder Truck'], when: When.vt },
  { group: 'CableEarthSwitch', sizes: ['Feeder Truck'], when: When.earthSwitchOrQc },
  { group: 'CouplingTruck', sizes: ['Coupling Truck'] },
  { group: 'VcbTruck', sizes: ['Coupling Truck'], when: When.vcb },
  { group: 'Riser', sizes: ['Riser', 'Riser Connection'] },
  { group: 'CableEarthSwitch', sizes: ['Riser', 'Riser Connection'], when: When.qc1 },
  { group: 'BusEarthTruck', sizes: ['Riser', 'Riser Connection'], when: When.qc2 },
  { group: 'MeteringRiser', sizes: ['Metering Riser', 'Metering Riser Connection'] },
  { group: 'MeteringTruck', sizes: ['Metering Riser', 'Metering Riser Connection'], when: When.vt },
  { group: 'BusEarthTruck', sizes: ['Metering Riser', 'Metering Riser Connection'], when: When.qc2 },
  { group: 'Metering', sizes: ['Metering'] },
  { group: 'MeteringTruck', sizes: ['Metering'], when: When.vt },
  { group: 'CableEarthSwitch', sizes: ['Metering'], when: When.qc1 },
  { group: 'BusEarthTruck', sizes: ['Metering'], when: When.qc2 },
  { group: 'IncomingVtCell', sizes: ['Incoming VT Cell'] },
  { group: 'IncomingVtCellTruck', sizes: ['Incoming VT Cell'], when: When.vt },
  { group: 'DisconnectorLinkWithoutFuse', sizes: ['Disconnector Link wo Fuse'] },
  { group: 'DLinkWithoutFuseTruck', sizes: ['Disconnector Link wo Fuse'], when: When.magnetLabel('MB3', 'MB4') },
  { group: 'Dummy', sizes: ['Dummy'] },
  { group: 'SupportInsteadOfCt', sizes: ['Support Instead of CT'] },
  ],
  itemsByGroup: {
    FeederTruck: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'BusBootCap', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 2 },
      { part: 'BusBootCoverGes2553', quantity: 1 },
      { part: 'BusbarWallBushing36Kv', quantity: 6 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    CouplingTruck: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 5 },
      { part: 'BusBootCap', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 2 },
      { part: 'BusBootCoverGes2553', quantity: 1 },
      { part: 'BusbarWallBushing36Kv', quantity: 6 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    Riser: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'IndoorCapacitiveDividerInsulator36Kv', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 3 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    MeteringRiser: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'IndoorCapacitiveDividerInsulator36Kv', quantity: 3 },
      { part: 'BusBootCap', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 3 },
      { part: 'BusbarWallBushing36Kv', quantity: 3 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    Metering: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorCapacitiveDividerInsulator36Kv', quantity: 3 },
      { part: 'BusBootCap', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 2 },
      { part: 'BusBootCoverGes2553', quantity: 1 },
      { part: 'BusbarWallBushing36Kv', quantity: 3 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    IncomingVtCell: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 3 },
      { part: 'BusbarWallBushing36Kv', quantity: 3 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    DisconnectorLinkWithoutFuse: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 3 },
      { part: 'BusbarWallBushing36Kv', quantity: 6 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    Dummy: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'BusBootCoverGes662', quantity: 2 },
      { part: 'BusBootCoverGes2553', quantity: 1 },
      { part: 'RubberGasketing', quantity: 5 },
    ],
    SupportInsteadOfCt: [
      { part: 'IndoorCapacitiveDividerInsulator36Kv', quantity: 3 },
    ],
    VcbTruck: [
      { part: 'EarthingSwitchAuxSwitch5NC5NO', quantity: 1 },
      { part: 'ContactFinger1250A', quantity: 6, when: When.cbCurrentAtMost(1250) },
      { part: 'ContactFinger2500A', quantity: 6, when: When.cbCurrentAbove(1250) },
    ],
    MeteringTruck: [
      { part: 'EarthingSwitchAuxSwitch5NC5NO', quantity: 1 },
      { part: 'HartingHanD64PosMaleInsert', quantity: 1 },
      { part: 'HartingHanD64PosFemaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanDFemaleCrimpContact', quantity: 50 },
      { part: 'HartingHanDMaleCrimpContact', quantity: 50 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'KontactStuckFuseBased9435', quantity: 6 },
      { part: 'KontactStuckFuseBased9436', quantity: 6 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'ContactFinger1250A', quantity: 3 },
    ],
    IncomingVtCellTruck: [
      { part: 'HartingHanD64PosMaleInsert', quantity: 1 },
      { part: 'HartingHanD64PosFemaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanDFemaleCrimpContact', quantity: 50 },
      { part: 'HartingHanDMaleCrimpContact', quantity: 50 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'KontactStuckFuseBased9435', quantity: 6 },
      { part: 'KontactStuckFuseBased9436', quantity: 6 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'ContactFinger1250A', quantity: 3 },
    ],
    DLinkWithoutFuseTruck: [
      { part: 'EarthingSwitchAuxSwitch5NC5NO', quantity: 1 },
      { part: 'HartingHanD64PosMaleInsert', quantity: 1 },
      { part: 'HartingHanD64PosFemaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanDFemaleCrimpContact', quantity: 50 },
      { part: 'HartingHanDMaleCrimpContact', quantity: 50 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'IndoorPostInsulator36Kv', quantity: 6 },
      { part: 'ContactFinger1250A', quantity: 6, when: When.cbCurrentAtMost(1250) },
      { part: 'ContactFinger2500A', quantity: 6, when: When.cbCurrentAbove(1250) },
    ],
    RearVtTruck: [
      { part: 'HartingHanD64PosMaleInsert', quantity: 1 },
      { part: 'HartingHanD64PosFemaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanDFemaleCrimpContact', quantity: 50 },
      { part: 'HartingHanDMaleCrimpContact', quantity: 50 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
    ],
    CableEarthSwitch: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'EarthingSwitchBlattfeder', quantity: 2 },
    ],
    BusEarthTruck: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'HartingHanD64PosMaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanDMaleCrimpContact', quantity: 50 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'IndoorPostInsulator36Kv', quantity: 3 },
      { part: 'ContactFinger1250A', quantity: 3 },
      { part: 'EarthingSwitchBlattfeder', quantity: 2 },
    ],
    RearFixVt: [
      { part: 'KontactStuckFuseBased9435', quantity: 6 },
      { part: 'KontactStuckFuseBased9436', quantity: 6 },
    ],
  },
};
