// src/utils/mechanical/simoprimeA4.ts
//
// The AIS-SIMOPRIME-A4 estimate sheet: which baskets a cell picks up, and what
// each basket consists of. Generated from the Eplanix MVC app's own
// catalogue — see parts.ts for where the parts themselves are described.

/** "IF F01-F06: W Stricker Pin", as the sheet writes it. */
const STRIKER_PIN_LABELS = ['F01', 'F02', 'F03', 'F04', 'F05', 'F06'];

import { MechanicalCatalog, When } from './catalog';

export const SIMOPRIMEA4_CATALOG: MechanicalCatalog = {
  panelType: 'AIS-SIMOPRIME-A4',
  baskets: [
  { group: 'FeederTruck', sizes: ['Feeder Truck'] },
  { group: 'VcbTruck', sizes: ['Feeder Truck'], when: When.vcb },
  { group: 'RearVtTruck', sizes: ['Feeder Truck'], when: When.vt },
  { group: 'CableEarthSwitch', sizes: ['Feeder Truck'], when: When.qc1 },
  { group: 'CouplingTruck', sizes: ['Coupling Truck'] },
  { group: 'VcbTruck', sizes: ['Coupling Truck'], when: When.vcb },
  { group: 'Riser', sizes: ['Riser'] },
  { group: 'MeteringRiser', sizes: ['Metering Riser'] },
  { group: 'MeteringTruck', sizes: ['Metering Riser'], when: When.vt },
  { group: 'BusEarthSwitch', sizes: ['Metering Riser'], when: When.qc2 },
  { group: 'RiserConnection', sizes: ['Riser Connection'] },
  { group: 'CableEarthSwitch', sizes: ['Riser Connection'], when: When.qc1 },
  { group: 'MeteringRiserConnection', sizes: ['Metering Riser Connection'] },
  { group: 'MeteringTruck', sizes: ['Metering Riser Connection'], when: When.vt },
  { group: 'CableEarthSwitch', sizes: ['Metering Riser Connection'], when: When.qc1 },
  { group: 'BusEarthSwitch', sizes: ['Metering Riser Connection'], when: When.qc2 },
  { group: 'Metering', sizes: ['Metering'] },
  { group: 'MeteringTruck', sizes: ['Metering'], when: When.vt },
  { group: 'BusEarthSwitch', sizes: ['Metering'], when: When.qc2 },
  { group: 'IncomingVtCell', sizes: ['Incoming VT Cell'] },
  { group: 'IncomingVtCellTruck', sizes: ['Incoming VT Cell'], when: When.vt },
  { group: 'DisconnectorLinkWithoutFuse', sizes: ['Disconnector Link wo Fuse'] },
  { group: 'DLinkWithoutFuseTruck', sizes: ['Disconnector Link wo Fuse'], when: When.vt },
  { group: 'Dummy', sizes: ['Dummy'] },
  { group: 'CellsWithCapacitiveIsolatorsWithoutCt', sizes: ['Cells w Capacitive Isolators & wo CT'] },
  { group: 'SupportInsteadOfCt', sizes: ['Support Instead of CT'] },
  ],
  itemsByGroup: {
    FeederTruck: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 3 },
      { part: 'BusbarWallBushing800', quantity: 6, when: When.panelWidth(800) },
      { part: 'BusbarWallBushing1000', quantity: 6, when: When.panelWidth(1000) },
      { part: 'TensorLockAngle', quantity: 1, when: When.cbType('3AE5') },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    CouplingTruck: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 5 },
      { part: 'BusbarWallBushing800', quantity: 6, when: When.panelWidth(800) },
      { part: 'BusbarWallBushing1000', quantity: 6, when: When.panelWidth(1000) },
      { part: 'TensorLockAngle', quantity: 1, when: When.cbType('3AE5') },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    Riser: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 10 },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    MeteringRiser: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 10 },
      { part: 'BusbarWallBushing800', quantity: 3, when: When.panelWidth(800) },
      { part: 'TensorLockAngle', quantity: 1, when: When.vt },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    RiserConnection: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 8 },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    MeteringRiserConnection: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 6 },
      { part: 'BusbarWallBushing800', quantity: 3, when: When.panelWidth(800) },
      { part: 'TensorLockAngle', quantity: 1, when: When.vt },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    Metering: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 3 },
      { part: 'BusbarWallBushing800', quantity: 3, when: When.panelWidth(800) },
      { part: 'TensorLockAngle', quantity: 1, when: When.vt },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    IncomingVtCell: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 6 },
      { part: 'BusbarWallBushing800', quantity: 3, when: When.panelWidth(800) },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    DisconnectorLinkWithoutFuse: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 3 },
      { part: 'BusbarWallBushing800', quantity: 6, when: When.panelWidth(800) },
      { part: 'BusbarWallBushing1000', quantity: 6, when: When.panelWidth(1000) },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    Dummy: [
      { part: 'QuarterTurnLock', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 3 },
      { part: 'SelfAdhesiveGasket', quantity: 20, when: When.ipAndWidth(42, 1000) },
      { part: 'SelfAdhesiveGasket', quantity: 19, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 9, when: When.ipAndWidth(42, 1000) },
      { part: 'SealingStrip', quantity: 8, when: When.ipAndWidth(42, 800) },
      { part: 'SealingStrip', quantity: 6, when: When.ipAndWidth(41, 1000) },
      { part: 'SealingStrip', quantity: 5, when: When.ipAndWidth(41, 800) },
    ],
    CellsWithCapacitiveIsolatorsWithoutCt: [
      { part: 'IndoorPostInsulator24Kv', quantity: -3 },
      { part: 'IndoorCapacitiveDividerInsulator24Kv', quantity: 3 },
    ],
    SupportInsteadOfCt: [
      { part: 'IndoorCapacitiveDividerInsulator24Kv', quantity: 3 },
    ],
    VcbTruck: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'VtFuseLinkClip', quantity: 6, when: When.cbTypeWithVt('3AH5') },
      { part: 'KontaktStuckBayka24393', quantity: 3, when: When.cbTypeWithVt('3AE5') },
      { part: 'KontaktStuckBayka24394', quantity: 3, when: When.cbTypeWithVt('3AE5') },
      { part: 'ContactFinger1250A', quantity: 6, when: When.panelWidth(800) },
      { part: 'ContactFinger2500A', quantity: 6, when: When.panelWidth(1000) },
    ],
    MeteringTruck: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'HartingHanE24PosFemaleInsert', quantity: 1 },
      { part: 'HartingHanE24PosMaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'KontactStuckFuseBased9435', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'KontactStuckFuseBased9436', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'IndoorPostInsulator24Kv', quantity: 6 },
      { part: 'ContactFinger630A', quantity: 3 },
    ],
    IncomingVtCellTruck: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'HartingHanE24PosFemaleInsert', quantity: 1 },
      { part: 'HartingHanE24PosMaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'KontactStuckFuseBased9435', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'KontactStuckFuseBased9436', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'IndoorPostInsulator24Kv', quantity: 6 },
      { part: 'ContactFinger630A', quantity: 3 },
    ],
    DLinkWithoutFuseTruck: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'HartingHanE24PosFemaleInsert', quantity: 1 },
      { part: 'HartingHanE24PosMaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'KontactStuckFuseBased9435', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'KontactStuckFuseBased9436', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'IndoorPostInsulator24Kv', quantity: 6 },
      { part: 'ContactFinger1250A', quantity: 6, when: When.panelWidth(800) },
      { part: 'ContactFinger2500A', quantity: 6, when: When.panelWidth(1000) },
    ],
    RearVtTruck: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'HartingHanE24PosFemaleInsert', quantity: 1 },
      { part: 'HartingHanE24PosMaleInsert', quantity: 1 },
      { part: 'HartingHan24BBasePanel1Lever', quantity: 1 },
      { part: 'HartingHanBHoodSideEntry', quantity: 1 },
      { part: 'HartingHanCodingSystemGuidePin', quantity: 4 },
      { part: 'HartingHanCodingSystemGuideBushing', quantity: 4 },
      { part: 'KontactStuckFuseBased9435', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'KontactStuckFuseBased9436', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'KontaktStuckBayka24393', quantity: 6, when: When.anyLabel(STRIKER_PIN_LABELS) },
      { part: 'IndoorPostInsulator24Kv', quantity: 6 },
      { part: 'VtFuseLinkClip', quantity: 6 },
    ],
    CableEarthSwitch: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'EarthingLamel', quantity: 12 },
      { part: 'EarthingSwitchBlattfeder', quantity: 2 },
    ],
    BusEarthSwitch: [
      { part: 'EarthingSwitchAuxSwitch4NC4NO', quantity: 1 },
      { part: 'IndoorPostInsulator24Kv', quantity: 3 },
      { part: 'EarthingLamel', quantity: 12 },
      { part: 'EarthingSwitchBlattfeder', quantity: 2 },
    ],
  },
};
